export const COMPANY_INDUSTRIES = [
  "Technology / IT",
  "Software and ITES",
  "Fintech",
  "Banking",
  "Insurance",
  "Microfinance",
  "Telecommunications",
  "E-commerce",
  "Retail",
  "FMCG",
  "Food and Beverage",
  "Textile and Apparel",
  "Manufacturing",
  "Automotive",
  "Cement",
  "Steel and Metals",
  "Chemicals",
  "Fertilizers",
  "Oil and Gas",
  "Energy and Power",
  "Pharmaceuticals",
  "Healthcare and Hospitals",
  "Education",
  "Media and Entertainment",
  "Marketing and Advertising",
  "Consulting",
  "Real Estate",
  "Construction",
  "Logistics and Courier",
  "Aviation",
  "Hospitality and Tourism",
  "Agriculture",
  "Government and Public Sector",
  "Nonprofit / Development",
  "Other",
] as const

export const EMPLOYEE_RANGES = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1000+",
] as const

export const JOB_CATEGORIES = [
  "Software Engineering",
  "Data Science",
  "Product Management",
  "Design",
  "Marketing",
  "Finance",
  "Operations",
  "Sales",
  "HR",
  "Consulting",
] as const
