/** Notable Pakistani employers for recruiter onboarding autocomplete. Type-your-own still works. */
export const PAKISTANI_COMPANIES = [
  "10Pearls",
  "Abbott Pakistan",
  "Accenture Pakistan",
  "Adamjee Insurance",
  "Afiniti",
  "AGP Limited",
  "Airblue",
  "Al Baraka Bank Pakistan",
  "Al-Fatah",
  "Al-Ghazi Tractors",
  "Alfalah Insurance",
  "Alkaram Studio",
  "Allied Bank",
  "Arbisoft",
  "Artistic Milliners",
  "ARY Digital Network",
  "Askari Bank",
  "Atlas Honda",
  "Attock Petroleum",
  "Attock Refinery",
  "Bahria Town",
  "Bank Al Habib",
  "Bank Alfalah",
  "BankIslami Pakistan",
  "Baqai Medical University Hospital",
  "Bata Pakistan",
  "Bayer Pakistan",
  "Beaconhouse School System",
  "Bestway Cement",
  "Borjan",
  "Bykea",
  "Careem Pakistan",
  "Carrefour Pakistan",
  "ChenOne",
  "Cherat Cement",
  "Cinepax",
  "Citibank Pakistan",
  "CMPak (Zong 4G)",
  "Coca-Cola Beverages Pakistan",
  "Confiz",
  "Contour Software",
  "Cubix",
  "CureMD",
  "Cybernet",
  "Dalda Foods",
  "Daraz Pakistan",
  "Dawn Media Group",
  "Deloitte Pakistan",
  "Descon Engineering",
  "Devsinc",
  "DG Khan Cement",
  "DHA",
  "Dolmen Group",
  "Dubai Islamic Bank Pakistan",
  "Dunya News",
  "EBM (Peek Freans)",
  "Educative",
  "EFU Life",
  "Emaar Pakistan",
  "Emumba",
  "Engro Corporation",
  "Engro Fertilizers",
  "Engro Polymer",
  "EY Ford Rhodes",
  "Express Media Group",
  "Fatima Fertilizer",
  "Fatima Group",
  "Fauji Cement",
  "Fauji Fertilizer Company (FFC)",
  "Fauji Foods",
  "Fauji Foundation",
  "Faysal Bank",
  "Federal Board of Revenue (FBR)",
  "Finja",
  "First Women Bank",
  "Fly Jinnah",
  "Folio3",
  "Foodpanda Pakistan",
  "FrieslandCampina Engro Pakistan",
  "Gaditek",
  "Geo TV / Independent Media Corporation",
  "Getz Pharma",
  "GlaxoSmithKline Pakistan",
  "Gourmet Foods",
  "Graana",
  "Gul Ahmed Textile Mills",
  "Habib Bank Limited (HBL)",
  "Habib Metropolitan Bank",
  "Haleeb Foods",
  "Hamdard Laboratories",
  "Hascol Petroleum",
  "HBL Microfinance Bank",
  "Heavy Industries Taxila (HIT)",
  "Highnoon Laboratories",
  "Hilal Foods",
  "Hilton Pharma",
  "Honda Atlas Cars",
  "Hub Power Company (Hubco)",
  "HUM Network",
  "Hyundai Nishat Motor",
  "i2c Pakistan",
  "IBM Pakistan",
  "IBEX Pakistan",
  "Ideas by Gul Ahmed",
  "IGI Holdings",
  "Imtiaz Super Market",
  "Inbox Business Technologies",
  "Indus Motor Company (Toyota)",
  "Interloop",
  "Ismail Industries (CandyLand)",
  "Jazz (VEON Pakistan)",
  "JazzCash",
  "J. Junaid Jamshed",
  "Jang Group / Geo",
  "JS Bank",
  "JS Global",
  "Jubilee Life Insurance",
  "K&N's",
  "K-Electric",
  "Kalsoft",
  "KAPCO",
  "Karachi Port Trust",
  "KASB",
  "Khaadi",
  "Kia Lucky Motor",
  "Kohat Cement",
  "Kolson",
  "KPMG Pakistan",
  "Lucky Cement",
  "Lucky Core Industries",
  "Lucky Motor Corporation",
  "Maple Leaf Cement",
  "Mari Petroleum",
  "Martin Dow",
  "Master Motors",
  "MCB Bank",
  "Meezan Bank",
  "Metro Pakistan",
  "Microsoft Pakistan",
  "Millat Tractors",
  "Mitchell's Fruit Farms",
  "Mobilink Microfinance Bank",
  "Motive (KeepTruckin)",
  "Mustakbil",
  "NADRA",
  "National Bank of Pakistan (NBP)",
  "National Foods",
  "National Logistics Cell (NLC)",
  "Nayatel",
  "NayaPay",
  "Nestlé Pakistan",
  "NetSol Technologies",
  "Nishat Group",
  "Nishat Mills",
  "NorthBay Solutions",
  "Novartis Pakistan",
  "NRSP Microfinance Bank",
  "NTDC",
  "Oil and Gas Development Company (OGDCL)",
  "Olper's / FrieslandCampina",
  "Oracle Pakistan",
  "Outfitters",
  "Ovex Technologies",
  "Packages Limited",
  "Pak Suzuki Motor",
  "Pakistan Aeronautical Complex",
  "Pakistan International Airlines (PIA)",
  "Pakistan Oilfields Limited",
  "Pakistan Petroleum Limited (PPL)",
  "Pakistan Post",
  "Pakistan Railways",
  "Pakistan Refinery Limited",
  "Pakistan State Oil (PSO)",
  "Pakistan Stock Exchange (PSX)",
  "Pakistan Steel Mills",
  "Pakistan Telecommunication Company Limited (PTCL)",
  "PakWheels",
  "PARCO",
  "PepsiCo Pakistan",
  "Pfizer Pakistan",
  "PharmEvo",
  "Pioneer Cement",
  "Port Qasim Authority",
  "PostEx",
  "PriceOye",
  "ProCheck",
  "PTA",
  "PTV",
  "PwC Pakistan",
  "Qarshi Industries",
  "Reckitt Pakistan",
  "Retailo",
  "Rider",
  "Roots Millennium Schools",
  "Rozee.pk",
  "SadaPay",
  "Sami Pharmaceuticals",
  "Sanofi Pakistan",
  "Sapphire Retail",
  "Sapphire Textile Mills",
  "Sazgar Engineering",
  "SECP",
  "SereneAir",
  "Service Industries (Servis)",
  "Shan Foods",
  "Shell Pakistan",
  "Shezan International",
  "Shifa International Hospitals",
  "Silkbank",
  "Sindh Bank",
  "Soneri Bank",
  "Special Communications Organization (SCO)",
  "Standard Chartered Pakistan",
  "State Bank of Pakistan",
  "State Life Insurance",
  "StormFiber",
  "Style Textile",
  "Stylo",
  "Sui Northern Gas Pipelines (SNGPL)",
  "Sui Southern Gas Company (SSGC)",
  "Summit Bank",
  "Systems Limited",
  "Tapal Tea",
  "TCS",
  "Techlogix",
  "Telenor Microfinance Bank (Easypaisa)",
  "Telenor Pakistan",
  "Telemart",
  "Teradata Pakistan",
  "The Bank of Khyber",
  "The Bank of Punjab",
  "The City School",
  "The Searle Company",
  "Tintash",
  "Total Parco Pakistan",
  "TPL Corp",
  "TRG Pakistan",
  "Trax",
  "U Microfinance Bank",
  "Ufone",
  "Unilever Pakistan",
  "United Bank Limited (UBL)",
  "US Apparel and Textiles",
  "Utility Stores Corporation",
  "VentureDive",
  "WAPDA",
  "Wateen Telecom",
  "Zameen.com",
  "Ziauddin University / Hospital",
  "Zong 4G",
] as const

export const COMPANY_OTHER = "Other (type your own)"
