/** HEC-recognized universities and DAIs in Pakistan (including AJK and GB). */
export const PAKISTANI_UNIVERSITIES = [
  "Abasyn University, Peshawar",
  "Abbottabad University of Science and Technology (AUST)",
  "Abdul Wali Khan University, Mardan",
  "Aga Khan University",
  "Air University, Islamabad",
  "Al-Ghazali University, Karachi",
  "Al-Hamd Islamic University, Quetta",
  "Ali Institute of Education, Lahore",
  "Al-Karam International Institute, Bhera",
  "Al-Kawthar University, Karachi",
  "Al-Khair University, AJK",
  "Allama Iqbal Open University, Islamabad",
  "Aror University of Art, Architecture, Design and Heritage, Sukkur",
  "Baba Guru Nanak University, Nankana Sahib",
  "Bacha Khan University, Charsadda",
  "Bahauddin Zakariya University, Multan",
  "Bahria University, Islamabad",
  "Balochistan University of Engineering and Technology, Khuzdar",
  "Balochistan University of Information Technology, Engineering and Management Sciences (BUITEMS), Quetta",
  "Baqai Medical University, Karachi",
  "Beaconhouse National University, Lahore",
  "Begum Nusrat Bhutto Women University, Sukkur",
  "Benazir Bhutto Shaheed University Lyari, Karachi",
  "Benazir Bhutto Shaheed University of Technology and Skill Development, Khairpur Mirs",
  "Brains Institute, Peshawar",
  "Capital University of Science and Technology (CUST), Islamabad",
  "CECOS University of Information Technology and Emerging Sciences, Peshawar",
  "Cholistan University of Veterinary and Animal Sciences, Bahawalpur",
  "City University of Science and Information Technology, Peshawar",
  "Commecs Institute of Business and Emerging Sciences, Karachi",
  "COMSATS University Islamabad",
  "Dadabhoy Institute of Higher Education, Karachi",
  "Dar-ul-Madina International University, Islamabad",
  "Dawood University of Engineering and Technology, Karachi",
  "DHA Suffa University, Karachi",
  "Dow University of Health Sciences, Karachi",
  "Emaan Institute of Management and Sciences, Karachi",
  "Emerson University, Multan",
  "Faisalabad Medical University, Faisalabad",
  "Fatima Jinnah Medical University, Lahore",
  "Fatima Jinnah Women University, Rawalpindi",
  "Federal Urdu University of Arts, Sciences and Technology, Islamabad",
  "Forman Christian College (FCCU), Lahore",
  "Foundation University, Islamabad",
  "Gambat Institute of Medical Sciences, Khairpur",
  "Gandhara University, Peshawar",
  "Ghazi National Institute of Engineering and Sciences, Dera Ghazi Khan",
  "Ghazi University, Dera Ghazi Khan",
  "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI), Topi",
  "GIFT University, Gujranwala",
  "Gomal University, Dera Ismail Khan",
  "Government College for Women University, Faisalabad",
  "Government College for Women University, Sialkot",
  "Government College University (GCU), Faisalabad",
  "Government College University (GCU), Hyderabad",
  "Government College University (GCU), Lahore",
  "Government Sadiq College Women University, Bahawalpur",
  "Greenwich University, Karachi",
  "Habib University, Karachi",
  "Hajvery University, Lahore",
  "Hamdard University, Karachi",
  "HANDS Institute of Development Studies, Karachi",
  "Hazara University, Mansehra",
  "Health Services Academy (HSA), Islamabad",
  "HITEC University, Taxila",
  "Hyderabad Institute for Technology and Management Sciences",
  "Ibadat International University, Islamabad",
  "Ibn-e-Sina University, Mirpurkhas",
  "ILMA University, Karachi",
  "Imperial College of Business Studies, Lahore",
  "Indus University, Karachi",
  "Indus Valley School of Art and Architecture, Karachi",
  "Information Technology University (ITU), Lahore",
  "Institute for Art and Culture, Lahore",
  "Institute of Business Administration (IBA), Karachi",
  "Institute of Business Management (IoBM), Karachi",
  "Institute of Management Sciences (IMSciences), Peshawar",
  "Institute of Management Sciences, Lahore",
  "Institute of Space Technology (IST), Islamabad",
  "International Institute of Science, Arts and Technology, Gujranwala",
  "International Islamic University Islamabad (IIUI)",
  "Iqra National University, Peshawar",
  "Iqra University, Karachi",
  "Islamia College University, Peshawar",
  "Islamia University of Bahawalpur",
  "Isra University, Hyderabad",
  "Jinnah Sindh Medical University, Karachi",
  "Jinnah University for Women, Karachi",
  "Kalam Bibi International Women Institute, Bannu",
  "Karachi Institute of Economics and Technology (PAF-KIET)",
  "Karachi Institute of Technology and Entrepreneurship (KITE)",
  "Karachi Metropolitan University",
  "Karachi School of Business and Leadership (KSBL)",
  "Karakoram International University, Gilgit",
  "KASB Institute of Technology, Karachi",
  "Khwaja Fareed University of Engineering and Information Technology, Rahim Yar Khan",
  "Khushal Khan Khattak University, Karak",
  "Khyber Medical University, Peshawar",
  "The University of Agriculture, Peshawar",
  "King Edward Medical University, Lahore",
  "Kinnaird College for Women, Lahore",
  "Kohat University of Science and Technology",
  "Kohsar University, Murree",
  "Lahore College for Women University",
  "Lahore Garrison University",
  "Lahore Institute of Science and Technology",
  "Lahore Leads University",
  "Lahore School of Economics",
  "Lahore University of Biological and Applied Sciences",
  "Lahore University of Management Sciences (LUMS)",
  "Lasbela University of Agriculture, Water and Marine Sciences",
  "Liaquat University of Medical and Health Sciences, Jamshoro",
  "Malir University of Science and Technology, Karachi",
  "Mehran University of Engineering and Technology, Jamshoro",
  "Metropolitan University Karachi",
  "Millennium Institute of Technology and Entrepreneurship (MITE), Karachi",
  "Minhaj University, Lahore",
  "Mir Chakar Khan Rind University of Technology, Dera Ghazi Khan",
  "Mir Chakar Khan Rind University, Sibi",
  "Mirpur University of Science and Technology (MUST), AJK",
  "Mohi-ud-Din Islamic University, AJK",
  "Muhammad Ali Jinnah University (MAJU), Karachi",
  "Muhammad Nawaz Shareef University of Agriculture, Multan",
  "Muhammad Nawaz Sharif University of Engineering and Technology, Multan",
  "Multan University of Science and Technology",
  "MY University, Islamabad",
  "Namal University, Mianwali",
  "National College of Arts (NCA), Lahore",
  "National College of Business Administration and Economics, Lahore",
  "National Defence University, Islamabad",
  "National Skills University, Islamabad",
  "National Textile University, Faisalabad",
  "National University of Computer and Emerging Sciences (FAST-NUCES)",
  "National University of Medical Sciences (NUMS), Rawalpindi",
  "National University of Modern Languages (NUML), Islamabad",
  "National University of Pakistan",
  "National University of Sciences and Technology (NUST), Islamabad",
  "National University of Technology (NUTECH), Islamabad",
  "NED University of Engineering and Technology, Karachi",
  "Newports Institute of Communications and Economics, Karachi",
  "NFC Institute of Engineering and Technology, Multan",
  "Nishtar Medical University, Multan",
  "Northern University, Nowshera",
  "Nur International University, Lahore",
  "PAF Air War College Institute, Karachi",
  "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology (PAF-IAST), Haripur",
  "Pakistan Global Institute, Rawat",
  "Pakistan Institute of Development Economics (PIDE), Islamabad",
  "Pakistan Institute of Engineering and Applied Sciences (PIEAS), Islamabad",
  "Pakistan Institute of Fashion and Design, Lahore",
  "Pakistan Military Academy, Abbottabad",
  "Pakistan Naval Academy, Karachi",
  "Peoples University of Medical and Health Sciences for Women, Nawabshah",
  "Pir Mehr Ali Shah Arid Agriculture University, Rawalpindi",
  "Preston Institute of Management, Science and Technology, Karachi",
  "Preston University, Karachi",
  "Preston University, Kohat",
  "Punjab Tianjin University of Technology, Lahore",
  "Punjab University of Technology, Rasul",
  "Qarshi University, Lahore",
  "Quaid-e-Awam University of Engineering, Sciences and Technology, Nawabshah",
  "Quaid-i-Azam University, Islamabad",
  "Qurtuba University of Science and Information Technology, Dera Ismail Khan",
  "Rashid Latif Khan University, Lahore",
  "Rawalpindi Medical University",
  "Rawalpindi Women University",
  "Riphah International University, Islamabad",
  "Saifee Burhani University, Karachi",
  "Salim Habib University, Karachi",
  "Sardar Bahadur Khan Women's University, Quetta",
  "Sarhad University of Science and Information Technology, Peshawar",
  "Shah Abdul Latif University, Khairpur",
  "Shaheed Allah Buksh Soomro University of Art, Design and Heritages, Jamshoro",
  "Shaheed Benazir Bhutto City University, Karachi",
  "Shaheed Benazir Bhutto Dewan University, Karachi",
  "Shaheed Benazir Bhutto University, Sheringal",
  "Shaheed Benazir Bhutto University of Veterinary and Animal Sciences, Sakrand",
  "Shaheed Benazir Bhutto University, Shaheed Benazirabad",
  "Shaheed Benazir Bhutto Women University, Peshawar",
  "Shaheed Mohtarma Benazir Bhutto Medical University, Larkana",
  "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology (SZABIST)",
  "Shaheed Zulfiqar Ali Bhutto Medical University, Islamabad",
  "Shaheed Zulfiqar Ali Bhutto University of Law, Karachi",
  "Shifa Tameer-e-Millat University, Islamabad",
  "Shuhada-e-Army Public School University of Technology, Nowshera",
  "Sindh Agriculture University, Tandojam",
  "Sindh Institute of Management and Technology, Karachi",
  "Sindh Institute of Medical Sciences, Karachi",
  "Sindh Madressatul Islam University, Karachi",
  "Sir Syed CASE Institute of Technology, Islamabad",
  "Sir Syed University of Engineering and Technology, Karachi",
  "Sohail University, Karachi",
  "Sukkur IBA University",
  "Textile Institute of Pakistan, Karachi",
  "Thal University, Bhakkar",
  "The Azad Jammu and Kashmir University of Bhimber",
  "Bolan University of Medical and Health Sciences, Quetta",
  "The Grand Asian University, Sialkot",
  "The Green International University, Lahore",
  "Nazeer Hussain University, Karachi",
  "Shaikh Ayaz University, Shikarpur",
  "Sindh Institute of Physical Medicine and Rehabilitation, Karachi",
  "The Superior University, Lahore",
  "The University of Agriculture, Dera Ismail Khan",
  "The University of Agriculture, Swat",
  "The University of Faisalabad",
  "University of Larkano",
  "The Women University, Multan",
  "Times Institute, Multan",
  "UIT University, Karachi",
  "University of Agriculture, Faisalabad (UAF)",
  "University of Art and Culture, Jamshoro",
  "University of Azad Jammu and Kashmir, Muzaffarabad",
  "University of Balochistan, Quetta",
  "University of Baltistan, Skardu",
  "University of Buner",
  "University of Central Punjab (UCP), Lahore",
  "University of Chakwal",
  "University of Chenab, Gujrat",
  "University of Child Health Sciences, Lahore",
  "University of Chitral",
  "University of Education, Lahore",
  "University of Engineering and Technology (UET), Peshawar",
  "University of Engineering and Technology (UET), Lahore",
  "University of Engineering and Technology (UET), Mardan",
  "University of Engineering and Technology (UET), Taxila",
  "University of Engineering and Applied Sciences, Swat",
  "University of FATA",
  "University of Gujrat",
  "University of Gwadar",
  "University of Haripur",
  "University of Health Sciences, Lahore",
  "University of Home Economics, Lahore",
  "University of Jhang",
  "University of Karachi",
  "University of Kotli, AJK",
  "University of Lahore (UOL)",
  "University of Lakki Marwat",
  "University of Layyah",
  "University of Loralai",
  "University of Makran, Panjgur",
  "University of Malakand",
  "University of Management and Technology (UMT), Lahore",
  "University of Mianwali",
  "University of Modern Sciences, Tando Muhammad Khan",
  "University of Narowal",
  "University of Okara",
  "University of Peshawar",
  "University of Poonch, Rawalakot",
  "University of Sahiwal",
  "University of Sargodha",
  "University of Science and Technology, Bannu",
  "University of Sialkot",
  "University of Sindh, Jamshoro",
  "University of South Asia, Lahore",
  "University of Southern Punjab, Multan",
  "University of Sufism and Modern Sciences, Bhitshah",
  "University of Swabi",
  "University of Swat",
  "University of the Punjab, Lahore",
  "University of Turbat",
  "University of Veterinary and Animal Sciences (UVAS), Lahore",
  "University of Wah",
  "Virtual University of Pakistan",
  "Women University Swabi",
  "Women University Mardan",
  "Women University of Azad Jammu and Kashmir, Bagh",
  "Ziauddin University, Karachi",
] as const

export const UNIVERSITY_OTHER = "Other (type your own)"
